### ISSUE TITLE
ERROR: Failed to resolve: com.github.adrielcafe:AndroidAudioConverter:0.0.8

### ISSUE THREAD

**Issue by ghost** [adrielcafe/AndroidAudioConverter#35]
Can't be added as dependencies anymore.

**Comment by ghost** [comment]
build.gradle (app):

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "com.dno.diktafon"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.adrielcafe:AndroidAudioConverter:0.0.8'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.navigation:navigation-fragment:2.2.1'
    implementation 'androidx.navigation:navigation-ui:2.2.1'
    implementation 'com.airbnb.android:lottie:3.4.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:preference-v7:28.0.0'
}

**Comment by ayush-android** [comment]
You forgot to add following line in build.gradle (app):

**repositories {
    maven {
        url "https://jitpack.io"
    }
}**

Specially remember that you need to add above lines and dependency both in app level build.gradle file.
Then it will start to work perfectly.

Thanks

**Comment by ghost** [comment]
Thank you. Silly struggles as a new developer for android. Closing this issue now.
